### PR TITLE
Tox tests CI guide

### PR DESCRIPTION
**Pull request by iScrE4m**
I spent few days figuring out how to report coverage using Tox, thanks to the help of customer support I figured out that at least branch name had to be passed otherwise payload would lie about being accepted (it would report as HEAD, has to be MASTER), it's better to pass all of this since code is trying to get it :)

### CODE REVIEW

**Comment by iScrE4m** [comment]
Now that I'm checking out this repo's tox, it might actually not be as complex as I wrote it out to be. Could it be that only https://pypi.python.org/pypi/tox-travis is causing this?

**Comment by dblandin** [comment]
Hey @iScrE4m,

We're relying on commit info directly from `git` during out own test reporter runs on CircleCI, which is why we don't have to pass through the other CI environment variables.

If you're using a CI provider that doesn't provide reliable info from `git`, like `branch`, then you would have to pass the appropriate environment variables in we'll use that value first before falling back on the `git` commands.

Which CI provider are you using? I'd be fine with pointing users to [codeclimate_test_reporter/components/ci.py](https://github.com/codeclimate/python-test-reporter/blob/master/codeclimate_test_reporter/components/ci.py) for an up-to-date mapping of CI data. What do you think?

**Comment by iScrE4m** [comment]
Heym thanks for explaining a bit more! I'm still not exactly sure what Tox does to it etc. But I guess it doesn't matter I'm using Travis CI. Pointing to ci.py sounds fine to me - but I think it should be pointed to from readme/docs, noone should have to crawl and search the source for something he might need in some cases.

**Comment by dblandin** [comment]
>  I'm still not exactly sure what Tox does to it etc.

I don't think Tox manipulates the working directory but it does seem to strip out environment variables, hence the passenv requirement. So it depends on how the git repository is cloned and reset initially within the CI environment.

> but I think it should be pointed to from readme/docs

Agreed! That was my thinking as well.

**Comment by dblandin** [comment]
Going to close this PR for now. Let me know if you have any more questions!

**Pull request closed without merging**
