### PR TITLE
Updating for coverage v4.4

### PR DESCRIPTION
**Pull request by jonrkarr**
Coverage v4.4 changes how file names are reported in XML report files. For example
> <class ... filename="karr_lab_build_utils/__init__.py" ... name="__init__.py">

is changed to

> <class ... filename="__init__.py" ... name="__init__.py">

These commits update the test reporter to accommodate this change. The changes are compatible with v4.4 as well as earlier versions.

### CODE REVIEW

**Comment by dblandin** [comment]
Hey @jonrkarr!

This PR looks great. Thanks for the fix!

Would you mind addressing the Code Climate issues? I'd be fine with removing the inline comments. The added lines seem sufficiently intention-revealing to me.

Is the new version of `0.2.1a0` considered an alpha release by pip? Since we'll release a new version, would `0.2.2` or `0.2.2a0` be more appropriate? In either case, we usually bump versions in separate PRs to keep the version history independent from changes merged into master.

**Comment by jonrkarr** [comment]
Hi Devon,

After I created the pull request I noticed there's already an issue about
this. It would be best not to require a specific version of coverage
because that would preclude the use of future versions. The coveragepy
discussion sounds like the original author isn't going to revert the change
that broke python-test-reporter, so it sounds like the solution is to
generate complete file paths by combining the sources/source paths and the
paths in packages/package/classes/class. For cases with multiple source
paths, the author author will need to add an id to sources/source so they
can be linked to specific classes and file paths can be unambiguously be
resolved.

The changes are only affect a couple lines. Feel free to incorporate the
changes as you best see fit.

Regards
Jonathan

**Comment by dblandin** [comment]
> For cases with multiple source paths, the author author will need to add an id to sources/source so they can be linked to specific classes and file paths can be unambiguously be resolved.

That sounds like an important addition to make before supporting `coverage v4.4` . Would you suggest locking down to `<4.4` in the meantime while we figure that out?

We're also working on a new unified test reporter which will support python so I'm less concerned with the long-term maintainability of this particular repo.

https://github.com/codeclimate/test-reporter

**Comment by jonrkarr** [comment]
Using a specific version of coverage is fine for us for now.

I didn't read the coveragepy discussion until after I made the changes. Had
I read that first, I would have just specified a specific version for now
until coveragepy sorts out this issue.

**Comment by dblandin** [comment]
> Had I read that first, I would have just specified a specific version for now until coveragepy sorts out this issue.

Yep, that sounds reasonable to me too. Going to close this PR for now.

Thanks!

**Comment by jonrkarr** [comment]
Thanks for the quick response on this!

**Pull request closed without merging**
