### PR TITLE
add latin 1 format handling (cf issue #37)

### PR DESCRIPTION
**Pull request by BuonOmo**
This tiny change add a method called read_file_content, which tries to read a file as utf-8 first, and if this throws an error, read it as latin-1.

Also considering a PR to skip files with different encoding. However this changes more code : division by zero may occur when all files have a different encoding.

### CODE REVIEW

**Comment by dblandin** [comment]
Hey @BuonOmo,

Thank you for the PR! I just triggered a CircleCI build for this PR. Would you mind checking out the `py27` failure?

**Comment by BuonOmo** [comment]
Done @dblandin!

**Comment by dblandin** [comment]
@BuonOmo Awesome! Thanks so much!

Will ping back here when I've released a new version.

**Comment by dblandin** [comment]
Just released v0.2.1: https://pypi.python.org/pypi/codeclimate-test-reporter/0.2.1

**Pull request merged**
